name: CI

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.6.1"
      - name: Build
        run: |
          poetry install
          poetry build
      - name: Test
        run: |
          tox
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: output
          path: output
